// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUUpBtWqUVBboA6BJqavsT8c0AFRa5c0',
    appId: '1:983797582372:android:6cce98f82f20c5e66326b1',
    messagingSenderId: '983797582372',
    projectId: 'fitness-app-d3545',
    databaseURL: 'https://fitness-app-d3545-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-app-d3545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt8VEzNGqRmjCB26EDthr4ARQ4hrZ5OEQ',
    appId: '1:983797582372:ios:c44db7631b88d7666326b1',
    messagingSenderId: '983797582372',
    projectId: 'fitness-app-d3545',
    databaseURL: 'https://fitness-app-d3545-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-app-d3545.appspot.com',
    androidClientId: '983797582372-qi4uf3vin2qc81s1dbj0kai9fjvtict8.apps.googleusercontent.com',
    iosClientId: '983797582372-hpv7s6fiilof9lhnqrml2mvcr18du6m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
